# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colMSD_dgc <- function(mat, m) {
    .Call(`_pPCA_colMSD_dgc`, mat, m)
}

